//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foe_Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-8"" ?><configuration> <startup> <supportedRuntime version=""v4.0"" sku="".NETFramework,Version=v4.5"" /> </startup><appSettings> <add key=""Lable.Port1"" value=""MessageID""/> <add key=""Lable.Port2"" value=""SendingBaseTag""/> <add key=""Lable.Port3"" value=""SendingMachineName""/> <add key=""Lable.Port4"" value=""MessageQueuePathName""/> <add key=""Lable.Port5"" value=""CustomField1""/> <add key=""Lable.Port6"" value=""CustomField2""/> <add key=""Body.Port1"" value=""DataMode""/> <add key=""Body.Port2"" value=""DataModeID""/> <add key=""Body.Port3"" value=""ExperimentID""/> <add key=""Body.Port4"" value=""BasePenType""/> <add key=""Body.Port5"" value=""BasePenTypeID""/> <add key=""Body.Port6"" value=""MID""/> <add key=""Body.Port7"" value=""StationTag""/> <add key=""Body.Port8"" value=""DateTime""/> <add key=""Body.Port9"" value=""Path1""/> <add key=""Body.Port10"" value=""EquipmentID1""/> <add key=""Body.Port11"" value=""Path2""/> <add key=""Body.Port12"" value=""EquipmentID2""/></appSettings></configuration>")]
        public string val {
            get {
                return ((string)(this["val"]));
            }
        }
    }
}
